### ISSUE TITLE
Quran zip URL

### ISSUE THREAD

**Issue by Nourtirga** [Five-Prayers/five-prayers-android#2]
What's the URL for for downloading quran zip file ? (QURAN_IMAGES_ZIP_URL)

**Comment by HichamBI** [comment]
Hello,

You can download the zip from [here](https://github.com/Five-Prayers/quran-pages/releases/download/1.0.0/quran_madani_images_1.0.0.zip)
Or consider this project if you want to create your own images : [quran.com-images](https://github.com/quran/quran.com-images)

Those fonts and pages belong to [the King Fahd Quran Complex in Saudia Arabia](https://qurancomplex.gov.sa/)

BR

**Comment by Nourtirga** [comment]
Thank you very much.
