### ISSUE TITLE
Can't manually set location

### ISSUE THREAD

**Issue by DragoonFX** [Five-Prayers/five-prayers-android#20]
My device is running resurrection remix 5.8.5 without gapps installed. I have turned on "set location manually" but when I search for a city in the "Actual location", nothing happens.

 - App Version: 2.3.0-R
 - Device: Galaxy Note 3 (sm-n9005)
 - OS: Android 7.1.2

**Comment by HichamBI** [comment]
Hello @DragoonFX 

Thanks for reporting this issue.

The GeocodingAPI I used changed there endpoint from photon.komoot.de/api to photon.komoot.io/api.

I'll do a fix verry soon.
 
BR,

**Comment by DragoonFX** [comment]
Oh I see,
JazakAllah Khair @HichamBI

**Comment by HichamBI** [comment]
Fixed on 2.3.1 e0a3f822cc54e1d76b524111b4ba9ef6ebfd78ee

Enjoy.
