### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by ahmed-tasaly** [Five-Prayers/five-prayers-android#22]
Assalamo alaykom

**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Arabic translation for the app.

**_Thanks in advance_**

**Comment by HichamBI** [comment]
Salam @ahmed-tasaly ,

The application is translated in arabic, french, and english. It depend on your phone language.

BR,

**Comment by ahmed-tasaly** [comment]
@HichamBI 
But can you add a separate option for the language
Because my phone language is English and I would like to have this app in Arabic 
Thanks in advance
جزاك الله خيرا

**Comment by HichamBI** [comment]
Fixed in 2.5.0
