### ISSUE TITLE
is there a way to not have notification from this app?

### ISSUE THREAD

**Issue by rezad1393** [Five-Prayers/five-prayers-android#25]
I use this app to calculate prayers times but I dont use the notification part.

is there a way to not have notification from this app?
other that the OS way I mean.
some older version of android dont have the ability to mute notifications based on channels.

**Comment by HichamBI** [comment]
Hi @rezad1393 

There is no way to mute notifications directly from the app.

I've marked this issue as an enhancement and I'll try to do something in the next release.

BR.

**Comment by HichamBI** [comment]
Fixed in (2.6.0) #26
