### ISSUE TITLE
manual setting of location

### ISSUE THREAD

**Issue by ahmed-tasaly** [Five-Prayers/five-prayers-android#34]
**To Reproduce**
1. Directly after installing of the app and opening it
2. swipe till reach location part 
3. it asks for the location 
4. if I efuse to allow location as i would like to set it manually afterwards 
5. This error appears 

![IMG_20220719_232826](https://user-images.githubusercontent.com/64969309/179851762-4af84aae-5935-4a37-af93-5cfe4c131a6c.jpg)

**Expected behavior**
To allow me to skip this part and set the location manually

**Smartphone (please complete the following information):**
 - Device: [ Poco F3 ]
 - OS: [ Android 12 -- MIUI 13 ]

**Comment by HichamBI** [comment]
Fixed in 2.0.7
