### ISSUE TITLE
Cannot turn on notifications for an app. It is greyed out. 

### ISSUE THREAD

**Issue by pinoholo** [Five-Prayers/five-prayers-android#51]
It says: At your request, Android is blocking this app's notifications from appearing on this device

I'm on a13, Maybe because app do not ask for Notification Permission for Opt-In Notifications?

**Comment by HichamBI** [comment]
Hello,

I published a fix for this. It will be available soon.
https://github.com/Five-Prayers/five-prayers-android/releases/tag/2.8.2
