### ISSUE TITLE
Prayer Notifications and Adhan Not Working on Android 9 & 10

### ISSUE THREAD

**Issue by rai61354** [Five-Prayers/five-prayers-android#52]
I've installed your app few months ago from plays tore and everything was perfect. But now I updated this app and after that prayers notifications and adhan not working on my Huawei Nova 3i and Huawei Y9 Prime (2019) and Huawei Mate 10 Lite. I've tested this app on these three devices Android 9 and Android 10. I didn't faced any app crash just notifications and adhan not working.

I've these 3 devices only maybe other users facing same issue on their different devices too. Kindly prayer times notifications issue ASAP because your app is very useful for us.

**Comment by HichamBI** [comment]
Hello,

If you dont receive notifications, it's may be because your phone is blocking the application from sending notifications. Some manufacturers have batterie saving policies and blocking all background services. Five Prayers application is using background services to schedule prayer with precision. Please check if the application is permeated to have bachgroud services and able to send notifications. For more info you can check this link : 
https://dontkillmyapp.com/

**Comment by rai61354** [comment]
> Hello,
> 
> If you dont receive notifications, it's may be because your phone is blocking the application from sending notifications. Some manufacturers have batterie saving policies and blocking all background services. Five Prayers application is using background services to schedule prayer with precision. Please check if the application is permeated to have bachgroud services and able to send notifications. For more info you can check this link : https://dontkillmyapp.com/

Thanks for the quick response, as i said before your previous version working very well on my device and I enabled all the services even Islam360 prayer notifications working fine on my device as well. Only five prayers updated version not sending prayer notifications and adhan on my device. Also let me know five prayers adhan notification working on silent mod too? because I enabled all prayer notifications inside the app also give the location permission but notifications not working

**Comment by HichamBI** [comment]
Yes notifications works also if the phone is in silent mode. (Not the no disturb mode). Please verify in app parameters if the notifications are enabled. Be sur that the checkbox is checked.

**Comment by ShaheenDevelopers** [comment]
I checked all inboxes already. Well I'm still didn't receive any prayer notification.

**Comment by ShaheenDevelopers** [comment]
Aslam o alaikum bro hope you're doing well, Prayer notification and adhan sound works fine on SDK 33 just Samsung few model blocked the notifications. But two days ago I've upgraded your app on android sdk 34 after that i tested the app but reminder sound and notifications works fine but adhan sound not working. But when i downgraded SDK 34 to SDK 33 everything works fine again. Can you tell me what's the reason behind that? 🙄

**Comment by HichamBI** [comment]
Hello,

I've not tested the SDK 34 yet, so I cannot explain why sound are not working for the moment.
I'll close this issue, 

Not getting notifications are the most of the time a device issue (blocked by manifacturer or by the users).

BR,
