### ISSUE TITLE
Sorry, This is message 

### ISSUE THREAD

**Issue by ARBoyGo** [Five-Prayers/five-prayers-android#55]
السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ 
Assalamu Alaikum Wa Rahmatullahi Wabarakatuh

Sorry for creating issue, this is a message.
Please have a room in Matrix for this app, Also check out [QuranApp](https://github.com/AlfaazPlus/QuranApp) privacy respecting and open source project. 

Muslim devs need to work together. In Sha Allah will do one day.

**Comment by HichamBI** [comment]
السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ 

Thank you for your message.
I'll try to consider having a Matrix room for the app.

I'll be happy for working with anyone who want to help in this project _in shae ALLAH_.

Salam,

**Comment by ARBoyGo** [comment]
Any update?
