### ISSUE TITLE
[Question] official links and parameters for calculation methods

### ISSUE THREAD

**Issue by TorCzaf** [Five-Prayers/five-prayers-android#56]
Hi jazak Allah Kheer for this great app
I have a question,
What are the official links and parameters for these calculation methods please?
  
  -Ministry of religious affairs - Tunisia
  -Ministry of Islamic affairs - Morocco
  -Ministry of religious affairs and wakfs - Algeria
  -London unified prayer times
  -Jabatan kemajuan Islam - Malaysia
  -Mosquee de Paris - France
  -Angle 18° France
  -Angle 15° France

Thank You.

**Comment by HichamBI** [comment]
Hello,

Am not using any official link except the London unified prayer times : https://www.londonprayertimes.com/

For the others method, am using Al Adhan API to get prayer timings.

BR,
