### ISSUE TITLE
Last release contains Google Mobile Services libraries

### ISSUE THREAD

**Issue by IzzySoft** [Five-Prayers/five-prayers-android#57]
With the last release (2.10.0), the app contains libraries of Google Mobile Services – which are proprietary for one, and a possibly privacy issue on the other hand. If this was unintentionally (I assume it might have sneaked in as dependency of some other library you use), could you please investigate what it was and eliminate the problem? Should it have been intentionally, I kindly ask to reconsider that decision.

For now, I had to add the `NonFreeComp` anti-feature to [your app in my repo](https://apt.izzysoft.de/packages/com.hbouzidi.fiveprayers/) (will become visible with the next sync at around 6 pm UTC). By the way, that "Get it on F-Droid" badge links to itself – AFAIK your app is not on F-Droid.org. For my repo, you could [pick a badge here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it), F-Droid.org has a proper one as well. But better not use a badge suggesting the official repo unless your app is really listed there :wink:

**Comment by HichamBI** [comment]
Hello @IzzySoft 

First of all, thank you for message ! You're right, I unintentionally added the GMS dependency that was sneaked in a new library I use for the new Qibla Module =>  
implementation 'com.google.android.gms:play-services-location:20.0.0' 

This lib is not used, but I forgot to deleted it from my gradle file.

I'll will publish a new version 2.10.1 today (in 5/6 hours) to fix this issue.

I want also to thank you for publishing this app in your repo and I'll be proud to put your link and badge in the README file.

BR,
 @HichamBI

**Comment by IzzySoft** [comment]
Cool, thanks a lot! If you give me a ping once it's up (my updater would look for it in about 2h from now and thus miss it) I'll check ASAP manually.

**Comment by HichamBI** [comment]
Hello @IzzySoft 

I've just published a cleaned 2.10.1 release.
The compassqibla is here :  https://github.com/Five-Prayers/five-prayers-android/tree/main/compassqibla

BR,

**Comment by IzzySoft** [comment]
Ouch, looks like it's back again:

* GMS
* Google Play Core
* [Google Play In-App Reviews API](https://developer.android.com/guide/playcore/in-app-review) (this is probably the culprit dragging in the other two)

Can you please revert this again, @HichamBI?
