### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [Five-Prayers/five-prayers-android#59]
First of all, god bless you my brother, I've been using your app for more than a year now.

I'm trying to build the app with GitHub Actions in my fork, but it cannot build the release apk due to an error that I don't know, the debug apk is building normally, is there anything that I need to change? 

I took a look and even your tests failing, I think you're not using them anymore so maybe something is outdated.

I hope you'll take a look and help me a little bit.

https://github.com/JohnBetaro/five-prayers-android

**Comment by HichamBI** [comment]
Hello,

Unit test are failing after the last release, I'll fixe them soon. But the build is working, you can check my github action.

BR,
