### ISSUE TITLE
Azan sound error

### ISSUE THREAD

**Issue by SAI00YT** [Five-Prayers/five-prayers-android#60]
**Describe the bug**

**To Reproduce**
1. Go to 'settings'
2. Change the Azan sound
3. Scroll down to 'Azan sound'
4. See error: whenever I change the azan sound, the sound doesn't apply after I exit from the app

**Expected behavior**
The expected is that the azan sound will change.

**Smartphone (please complete the following information):**
 - Device: [e.g. galaxy A54 ]
 - OS: [e.g. android 13]
 - Browser [samsung internet browser 
 - Version [unknown]

**Additional context**

**Comment by HichamBI** [comment]
Issue not clear. Closed.
