### ISSUE TITLE
Automatic Adhan Silencing on Phone Tilt

### ISSUE THREAD

**Issue by jobbb2** [Five-Prayers/five-prayers-android#61]
Hello, thank you for your nice app!

I propose the addition of a feature that automatically switches the Adhan to silent mode when the user tilts their cell phone downwards. Because it's easier and faster to turn the phone over than finding the "down volume button".

Or you can add it as an alternative...

Best regards

**Comment by HichamBI** [comment]
Hello, Thank you for submitting this idea. I'll try to implement it.

**Comment by HichamBI** [comment]
Done in 2.12.0
